image:
  file: .gitpod.Dockerfile

tasks:
  - name: init dev environment
    before: poetry install --no-root --no-interaction

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode

    - d-biehl.robotcode
